include theos/makefiles/common.mk

BUNDLE_NAME = CoverflowMSettings
CoverflowMSettings_FILES = /mnt/d/codes/coverflowm/coverflowmsettings/CoverflowMSettingsController.mm
CoverflowMSettings_INSTALL_PATH = /Library/PreferenceBundles
CoverflowMSettings_FRAMEWORKS = UIKit QuartzCore CoreGraphics MessageUI Social Twitter
CoverflowMSettings_PRIVATE_FRAMEWORKS = Preferences
CoverflowMSettings_CFLAGS = -fobjc-arc
CoverflowMSettings_ARCHS = armv7 arm64
export ARCHS = armv7 arm64

include $(THEOS_MAKE_PATH)/bundle.mk
